#!/bin/bash
# Este script sirve para realizar backup en nuestro local de la DB contenida en docker

#DEFINICION VARIABLES

#DOCKER LOCAL
DOCKER_URL='letraslibres.local'
DOCKER_USER='root'
DOCKER_PWD='root'

DOCKER_DB_EXPORT_PATH='/var/www/html/db'
DOCKER_DB_USER='drupal8'
DOCKER_DB_PWD='drupal8'
DOCKER_DB_HOST='localhost'
DOCKER_DB_NAME='drupal8'

DOCKER_DRUPAL_PATH='/var/www/html/drupal8'

# Aqui meterle el usuario unico de quien vaya a usar el script (Ej. Ramiro)
today=$(date +%Y-%m-%dT%H.%I.%S)
DB_EXPORT_FILE_NAME='letraslibres-local-Pierre'"$today"'.sql'
DB_EXPORT_FILE_NAME_PATTERN='letraslibres-local-Pierre*.sql'

#FLUSH CASHES
echo "@ Connecting to your Docker:"
sshpass -p $DOCKER_PWD ssh $DOCKER_USER@$DOCKER_URL 'cd '"$DOCKER_DRUPAL_PATH"';echo "Flushing ...";drush cr all'

#BACKUP DB
echo "@ Backup DB:"
echo "$DB_EXPORT_FILE_NAME"
sshpass -p $DOCKER_PWD ssh $DOCKER_USER@$DOCKER_URL 'cd '"$DOCKER_DB_EXPORT_PATH"';mysqldump -u '"$DOCKER_DB_USER"' -p'"$DOCKER_DB_PWD"' -h '"$DOCKER_DB_HOST $DOCKER_DB_NAME"' > '"$DB_EXPORT_FILE_NAME"';echo "Last generated DB:";ls -t | head -1'

#COMPRIMIR DB
echo "@ Compress DB:"
sshpass -p $DOCKER_PWD ssh $DOCKER_USER@$DOCKER_URL 'cd '"$DOCKER_DB_EXPORT_PATH"';gzip '"$DB_EXPORT_FILE_NAME_PATTERN"';ls -t | head -1 '

echo "@ Process Finished."
