#!/bin/bash
# Este script sirve para instalar en nuestro local la DB de DEV/PROD
# Lo que hace es conectarse a un servidor remoto previamente configurado
# En dicho servidor flushea las cashes
# Realiza Backup de la DB
# Comprime la DB
# Y la baja a tu local, y finalmente la instala en tu docker Local
# y cómo bonus resetea la contraseña de drupal a 1

#DEFINICION VARIABLES

#REMOTO
SERV_SSH='projectname.dev'
SERV_REPO_DIR='/var/www/projectname'
SERV_DB_BACKUP_DIR='/home/ubuntu/db'
SERV_DB_USER='user'
SERV_DB_PWD='pwd'
SERV_DB_HOST='host'
SERV_DB_NAME='dbname'
DB_EXPORT_FILE_NAME='projectname-dev-$(date +%Y-%m-%dT%H.%I.%S).sql'
DB_EXPORT_FILE_NAME_PATTERN='projectname-dev*.sql'

#LOCAL
LOCAL_DB_IMPORT_PATH='/home/pierre/webapps/projectname/db/'

#DOCKER LOCAL
DOCKER_URL='projectname.local'
DOCKER_USER='root'
DOCKER_PWD='root'

DOCKER_DB_IMPORT_PATH='/var/www/html/db'
DOCKER_DB_USER='drupal8'
DOCKER_DB_PWD='drupal8'
DOCKER_DB_HOST='localhost'
DOCKER_DB_NAME='drupal8'

DOCKER_DRUPAL_PATH='/var/www/html/projectname'
DOCKER_DRUPAL_NEW_PWD='1'

#FLUSH CASHES
echo "@ Flushing caches in the following directory:"
ssh $SERV_SSH 'cd '"$SERV_REPO_DIR"';pwd;drupal cr all;'

#BACKUP DB
echo "@ Backing up DB in the following directory:"
ssh $SERV_SSH 'cd '"$SERV_DB_BACKUP_DIR"';pwd;mysqldump -u '"$SERV_DB_USER"' -p'"$SERV_DB_PWD"' -h '"$SERV_DB_HOST $SERV_DB_NAME"' > '"$DB_EXPORT_FILE_NAME"' '

#COMPRIMIR DB
echo "@ Zipping the DB in the following directory:"
ssh $SERV_SSH 'cd '"$SERV_DB_BACKUP_DIR"';pwd;gzip '"$DB_EXPORT_FILE_NAME_PATTERN"' '

#BAJAR DB CREADA
echo "@ Downloading the DB:"
scp $SERV_SSH:$SERV_DB_BACKUP_DIR/$(ssh $SERV_SSH 'ls -t '"$SERV_DB_BACKUP_DIR"'/ |head -1') $LOCAL_DB_IMPORT_PATH

#INSTALAR LA DB BAJADA
echo "@ Connecting to your Docker:"
sshpass -p $DOCKER_PWD ssh $DOCKER_USER@$DOCKER_URL 'cd '"$DOCKER_DB_IMPORT_PATH"';echo "Importing in Docker ...";echo `ls -t|head -1`;pv `ls -t|head -1`|gunzip|mysql -u '"$DOCKER_DB_USER"' -p'"$DOCKER_DB_PWD"' -h '"$DOCKER_DB_HOST"' '"$DOCKER_DB_NAME"

#RESETEAR LA CONTRASEÑA DE DRUPAL
echo "@ Reset Drupal Pwd:"
sshpass -p $DOCKER_PWD ssh $DOCKER_USER@$DOCKER_URL 'cd '"$DOCKER_DRUPAL_PATH"';drupal user:password:reset 1 '"$DOCKER_DRUPAL_NEW_PWD"';drupal cr all'
echo "@ Process Finished."
